spring:
  application:
    name: hik-isup
server:
  port: 16233

hik:
  platform:
    pushAddress: http://192.168.2.47:9080/iot/event/HK/callback
  stream:
    rtmp:
      #      公网对接填入公网地址
      ip: 192.168.2.235
      #      服务器本地地址
      listenIp: 192.168.2.235
      port: 7935
    http:
      #      公网对接填入公网地址
      ip: 192.168.2.235
      port: 7788
  isup:
    # last update
    # Fri Aug 06 11:51:16 CST 2021

    cmsServer:
      # 注册服务器监听地址(服务器本地地址)
      ip: 192.168.2.235
      port: 7660

    dasServer:
      # DAS地址（此处的IP和端口与设备网页端设置的平台IP地址和端口一致）
      ip: 192.168.2.235
      port: 7660

    smsServer:
      # 取流服务器地址端口（公网对接填入公网地址和端口）
      ip: 192.168.2.235
      port: 7665
      # 取流服务器监听地址端口(服务器本地地址)
      listenIp: 192.168.2.235
      listenPort: 7665

    smsBackServer:
      # 回放流媒体服务器地址端口（公网对接填入公网地址和端口）
      ip: 192.168.2.235
      port: 8000
      # 取流服务器监听地址端口(服务器本地地址)
      listenIp: 192.168.2.235
      listenPort: 8000

    voiceSmsServer:
      # 语音流媒体服务器地址端口（公网对接填入公网地址和端口）
      ip: 192.168.2.235
      port: 7500
      # 语音流媒体服务器监听地址端口(服务器本地地址)
      listenIp: 192.168.2.235
      listenPort: 7500

    alarmServer:
      # 报警服务器地址（公网对接填入公网地址和端口）
      ip: 192.168.2.235
      tcpPort: 7663
      udpPort: 7662
      # 报警服务器类型：
      # 0-只支持UDP协议上报
      # 1-支持UDP、TCP两种协议上报（ISUP4.0）
      # 2-MQTT(ISUP5.0) (MQTT复用TCP的端口)
      type: 2
      # 报警服务器监听地址端口
      listenIp: 192.168.2.235
      listenTcpPort: 7663
      listenUdpPort: 7662

    picServer:
      # 图片存储服务器地址：IUSP5.0版本接入端口建议固定为6011
      ip: 192.168.2.235
      port: 6120
      # 图片存储服务器类型：
      # 0-Tomcat
      # 1-VRB
      # 2-云存储
      # 3-KMS
      # 4-ISUP5.0
      type: 2
      # 图片存储服务器监听地址端口
      listenIp: 192.168.2.235
      listenPort: 6120

    # ISUP5.0登录秘钥
    isupKey: hik12345

    # 报警服务器打印事件模式
    # file=事件保存到文件中
    # console=事件打印在控制台上
    eventInfoPrintType: file
