spring:
  application:
    name: hik-isup
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: true
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
          # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
          url: jdbc:mysql://127.0.0.1:3306/isup?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
          username: root
          password: root
          hikari:
            # 最大连接池数量
            maxPoolSize: 20
            # 最小空闲线程数量
            minIdle: 10
            # 配置获取连接等待超时的时间
            connectionTimeout: 30000
            # 校验超时时间
            validationTimeout: 5000
            # 空闲连接存活最大时间，默认10分钟
            idleTimeout: 600000
            # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
            maxLifetime: 1800000
            # 多久检查一次连接的活性
server:
  port: 16233

mybatis-plus:
  # 自定义配置 是否全局开启逻辑删除 关闭后 所有逻辑删除功能将失效
  enableLogicDelete: true
  # 多包名使用 例如 com.oldwei.**.mapper,org.xxx.**.mapper
  mapperPackage: com.oldwei.**.mapper
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.oldwei.**.model
  global-config:
    dbConfig:
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      # 如需改为自增 需要将数据库表全部设置为自增
      idType: ASSIGN_ID

hik:
  isup:
    # last update
    # Fri Aug 06 11:51:16 CST 2021

    cmsServer:
      # 注册服务器监听地址(服务器本地地址)
      ip: 192.168.2.235
      port: 7660

    dasServer:
      # DAS地址（此处的IP和端口与设备网页端设置的平台IP地址和端口一致）
      ip: 192.168.2.235
      port: 7660

    smsServer:
      # 取流服务器地址端口（公网对接填入公网地址和端口）
      ip: 192.168.2.235
      port: 7665
      # 取流服务器监听地址端口(服务器本地地址)
      listenIp: 192.168.2.235
      listenPort: 7665

    smsBackServer:
      # 回放流媒体服务器地址端口（公网对接填入公网地址和端口）
      ip: 192.168.2.235
      port: 8000
      # 取流服务器监听地址端口(服务器本地地址)
      listenIp: 192.168.2.235
      listenPort: 8000

    voiceSmsServer:
      # 语音流媒体服务器地址端口（公网对接填入公网地址和端口）
      ip: 192.168.2.235
      port: 7500
      # 语音流媒体服务器监听地址端口(服务器本地地址)
      listenIp: 192.168.2.235
      listenPort: 7500

    alarmServer:
      # 报警服务器地址（公网对接填入公网地址和端口）
      ip: 192.168.2.235
      tcpPort: 7663
      udpPort: 7662
      # 报警服务器类型：
      # 0-只支持UDP协议上报
      # 1-支持UDP、TCP两种协议上报（ISUP4.0）
      # 2-MQTT(ISUP5.0) (MQTT复用TCP的端口)
      type: 2
      # 报警服务器监听地址端口
      listenIp: 192.168.2.235
      listenTcpPort: 7663
      listenUdpPort: 7662

    picServer:
      # 图片存储服务器地址：IUSP5.0版本接入端口建议固定为6011
      ip: 192.168.2.235
      port: 6120
      # 图片存储服务器类型：
      # 0-Tomcat
      # 1-VRB
      # 2-云存储
      # 3-KMS
      # 4-ISUP5.0
      type: 2
      # 图片存储服务器监听地址端口
      listenIp: 192.168.2.235
      listenPort: 6120

    # ISUP5.0登录秘钥
    isupKey: hik12345

    # 报警服务器打印事件模式
    # file=事件保存到文件中
    # console=事件打印在控制台上
    eventInfoPrintType: file
